#### 1. High Level Function

In [2]:
def add(x):
    return x + 1

def mul(x):
    return x*2

def apply(func,x):
    return func(x)

print("Addition :",add(11))
print("Miltiply :",mul(16))
print("High level function :",apply(add,12))

Addition : 12
Miltiply : 32
High level function : 13


#### 2. Lambda Function

In [7]:
square = lambda x: x**2
print(square(69))

4761


#### 3. Map, filter and reduce

In [8]:
from functools import reduce
words = ["apple", "banana", "cherry", "date", "elderberry"]
capitalized_words = list(map(lambda x: x.capitalize(), words))
b_words = list(filter(lambda x: x.startswith("b"), words))
concatenated_words = reduce(lambda x, y: x + " " + y, words)
print("Original Words:", words)
print("Capitalized Words:", capitalized_words)
print("Words Starting with 'b':", b_words)
print("Concatenated Words:", concatenated_words)

Original Words: ['apple', 'banana', 'cherry', 'date', 'elderberry']
Capitalized Words: ['Apple', 'Banana', 'Cherry', 'Date', 'Elderberry']
Words Starting with 'b': ['banana']
Concatenated Words: apple banana cherry date elderberry


#### 4. List comphrehension

In [6]:
my_list = [12, 22, 34, 4, 5]
result = [x * 2 for x in my_list]
print("Double list :",result)

my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
even_numbers = [x for x in my_list if x % 2 == 0]
print("All the even numbers are :",even_numbers)

from functools import reduce
data = [1, 2, 3, 4, 5]
product = [reduce(lambda x, y: x * y, data)]
print(product)

Double list : [24, 44, 68, 8, 10]
All the even numbers are : [2, 4, 6, 8, 10]
[120]


#### 5. Map

In [9]:
# finding the doubled number
numbers = [1, 2, 3, 4, 5]
doubled_numbers = list(map(lambda x: x * 2, numbers))
print(doubled_numbers)

# finding square roots
numbers = [1, 2, 3, 4, 5]
squared_numbers = list(map(lambda x: x ** 2, numbers))
print(squared_numbers)

# converting into uppercase
words = ["apple", "banana", "cherry"]
uppercase_words = list(map(lambda x: x.upper(), words))
print(uppercase_words)

# finding the first letter from a word
words = ["apple", "banana", "cherry"]
first_letters = list(map(lambda x: x[0], words))
print(first_letters)

# adding prefix to the names in the list
names = ["Alice", "Bob", "Charlie"]
prefixed_names = list(map(lambda x: "Mr. " + x, names))
print(prefixed_names)

# finding length of words in a list
words = ["apple", "banana", "cherry"]
word_lengths = list(map(len, words))
print(word_lengths)

# finding absolute values
numbers = [-1, -2, 3, -4, 5]
absolute_values = list(map(abs, numbers))
print(absolute_values)

# converting fehrenheit to celsius 
fahrenheit_temperatures = [32, 68, 86, 104]
celsius_temperatures = list(map(lambda f: (f - 32) * 5/9, fahrenheit_temperatures))
print(celsius_temperatures)

# stripping a sentence
sentences = ["  Hello,  ", "  World  ", "   "]
stripped_sentences = list(map(lambda x: x.strip(), sentences))
print(stripped_sentences)

# convert a decimal to binary
numbers = [7, 10, 15]
binary_numbers = list(map(lambda x: bin(x)[2:], numbers))
print(binary_numbers)

# to find last element of a list
nested_lists = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
last_elements = list(map(lambda x: x[-1], nested_lists))
print(last_elements)

# reversing a phrase
phrases = ["Hello world", "Good morning", "Python is great"]
reversed_phrases = list(map(lambda x: ' '.join(x.split()[::-1]), phrases))
print(reversed_phrases)

# finding factorial
import math
numbers = [1, 2, 3, 4, 5]
factorials = list(map(lambda x: math.factorial(x), numbers))
print(factorials)

# finding square roots
numbers = [1, 4, 9, 16, 25]
square_roots = list(map(math.sqrt, numbers))
print(square_roots)

# extract domain name from list of emails
emails = ["user@example.com", "admin@company.org", "test@domain.net"]
domains = list(map(lambda x: x.split('@')[1], emails))
print(domains)

[2, 4, 6, 8, 10]
[1, 4, 9, 16, 25]
['APPLE', 'BANANA', 'CHERRY']
['a', 'b', 'c']
['Mr. Alice', 'Mr. Bob', 'Mr. Charlie']
[5, 6, 6]
[1, 2, 3, 4, 5]
[0.0, 20.0, 30.0, 40.0]
['Hello,', 'World', '']
['111', '1010', '1111']
[3, 6, 9]
['world Hello', 'morning Good', 'great is Python']
[1, 2, 6, 24, 120]
[1.0, 2.0, 3.0, 4.0, 5.0]
['example.com', 'company.org', 'domain.net']


#### 6. Filter

In [11]:
# to find the even numbers
numbers = [1, 2, 3, 4, 5, 6]
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))
print(even_numbers)

# to find the words with 'a' in it
words = ["apple", "banana", "cherry", "date", "elderberry"]
a_words = list(filter(lambda word: 'a' in word, words))
print(a_words)

# finding out all the postive numbers from a list
numbers = [-2, 3, -5, 7, 0, 10, -12]
positive_numbers = list(filter(lambda x: x > 0, numbers))
print(positive_numbers)

# finding out all the prime numbers from a list
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            return False
    return True
numbers = [2, 3, 4, 5, 6, 7, 8, 9, 10]
prime_numbers = list(filter(is_prime, numbers))
print(prime_numbers)

# finding out all the names which are bigger than 5 letters
names = ["Alice", "Bob", "Charlie", "David", "Eve"]
long_names = list(filter(lambda name: len(name) > 5, names))
print(long_names)

# to find out all the mails with .com extension
emails = ["alice@example.com", "bob@example.org", "charlie@gmail.com", "david@example.com"]
com_emails = list(filter(lambda email: email.endswith(".com"), emails))
print(com_emails)

# to find out all the fruits whose word length is even in numbers
words = ["apple", "banana", "cherry", "date", "elderberry"]
even_length_words = list(filter(lambda word: len(word) % 2 == 0, words))
print(even_length_words)

# to filter out those fruits, whose length is bigger than 5 and have letter 'e' in them
words = ["apple", "banana", "cherry", "date", "elderberry"]
selected_words = list(filter(lambda word: len(word) > 5 and 'e' in word, words))
print(selected_words)

# filter out the numbers, which are either divisble by 3 or 5
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
filtered_numbers = list(filter(lambda x: x % 3 == 0 or x % 5 == 0, numbers))
print(filtered_numbers)

# filter out the words which are started with vowel
words = ["apple", "banana", "cherry", "date", "elderberry"]
vowel_starting_words = list(filter(lambda word: word[0].lower() in ['a', 'e', 'i', 'o', 'u'], words))
print(vowel_starting_words)

# filter out the students, whho have more marks than 90
students = [
    {"name": "Alice", "score": 95},
    {"name": "Bob", "score": 88},
    {"name": "Charlie", "score": 92},
    {"name": "David", "score": 78},
]
high_scorers = list(filter(lambda student: student["score"] > 90, students))
print(high_scorers)

# filter out the books which are published post 2000
books = [
    {"title": "Book 1", "year": 1998},
    {"title": "Book 2", "year": 2005},
    {"title": "Book 3", "year": 2010},
    {"title": "Book 4", "year": 1995},
]
recent_books = list(filter(lambda book: book["year"] > 2000, books))
print(recent_books)

# filter out all the unique numbers from a list
numbers = [1, 2, 2, 3, 4, 4, 5, 5]
unique_numbers = list(set(numbers))
print(unique_numbers)

# filter out all the files which are in text form
file_names = ["document.docx", "image.png", "report.pdf", "data.txt", "notes.txt"]
text_files = list(filter(lambda file: file.endswith(".txt"), file_names))
print(text_files)

# filter out the words which are in lowercase
words = ["apple", "Banana", "cherry", "Date", "elderberry"]
lowercase_words = list(filter(lambda word: word.islower(), words))
print(lowercase_words)

[2, 4, 6]
['apple', 'banana', 'date']
[3, 7, 10]
[2, 3, 5, 7]
['Charlie']
['alice@example.com', 'charlie@gmail.com', 'david@example.com']
['banana', 'cherry', 'date', 'elderberry']
['cherry', 'elderberry']
[3, 5, 6, 9, 10]
['apple', 'elderberry']
[{'name': 'Alice', 'score': 95}, {'name': 'Charlie', 'score': 92}]
[{'title': 'Book 2', 'year': 2005}, {'title': 'Book 3', 'year': 2010}]
[1, 2, 3, 4, 5]
['data.txt', 'notes.txt']
['apple', 'cherry', 'elderberry']


#### 7. Reduce

In [12]:
from functools import reduce

def add(a,b):
    return a + b
lst = [2,8,6,4,9,2]
print("Sum of all the numbers from the list is :",reduce(add,lst))

Sum of all the numbers from the list is : 31


#### 8. Finding the largest of the given number

In [14]:
from functools import reduce
lst = [2,8,6,4,9,2]
def large(x,y):
    return x if x > y else y
print("Largest number of the list using reduce is :", reduce(large,lst))

print("Largest number of the list using lambda is :", reduce(lambda x,y: x if x > y else y, lst))

Largest number of the list using reduce is : 9
Largest number of the list using lambda is : 9


#### 9. pass statement

In [16]:
lst = [2,8,6,4,9,2]
for i in lst:
    if i == 9:
        pass
    else:
        print("No pass keyword reached yet",i)

No pass keyword reached yet 2
No pass keyword reached yet 8
No pass keyword reached yet 6
No pass keyword reached yet 4
No pass keyword reached yet 2


#### 10. tuples

In [18]:
emp_tup = ()
print("Empty tuple :",emp_tup)

int_tup = (1,2,3,4)
print("Tuple with integer :", int_tup)

mix_tup = (1,2,6.7,"Meetul")
print("Tuple with mixed datatypes :", mix_tup)

nest_tup = ("Meetul", (1,2,3,4),(9,78))
print("Nested tuple :", nest_tup)

Empty tuple : ()
Tuple with integer : (1, 2, 3, 4)
Tuple with mixed datatypes : (1, 2, 6.7, 'Meetul')
Nested tuple : ('Meetul', (1, 2, 3, 4), (9, 78))


#### 11. Access elements in a tuple and error handling

In [3]:
tup = ("meetul", "shraddha", "manish")
print(tup[1])
print(tup[2])

try:
    print(tup[5])
except Exception as e:
    print(e)

shraddha
manish
tuple index out of range


#### 12. access tuple using float slicing and in nested tuple

In [4]:
tup = ("meetul", "shraddha", "manish")
try:
    print(tup[1.0])
except Exception as e:
    print(e)
    
nest_tup = ("Meetul", [2, 6, 8, 7], (7, 3, 4))
print(nest_tup[0][2])
print(nest_tup[2][1])

tuple indices must be integers or slices, not float
e
3


#### 13. negative indexing in tuple

In [5]:
tup = ("meetul", "shraddha", "manish")
print(tup[-2])
print(tup[-5:-1])

shraddha
('meetul', 'shraddha')


#### 14. Slicing in tuple

In [21]:
tup = ("meetul", "shraddha", "manish")
print(tup[0:2])
print(tup[:-2])
print(tup[:])

('meetul', 'shraddha')
('meetul',)
('meetul', 'shraddha', 'manish')


#### 15. del element and tuple in tuple using index and value using error handling and than accessing the deleted tuple 

In [23]:
tup = ("meetul", "shraddha", "manish")
try:
    del tup[2]
    print(tup)
except Exception as e:
    print(e)
    
del tup
try:
    print(tup)
except Exception as e:
    print(e)

'tuple' object doesn't support item deletion
name 'tup' is not defined


#### 16. repeated tuple = tuple * 3

In [24]:
tup = ("meetul", "shraddha", "manish")
print("Original tuple :",tup)
print("New tuple :", tup * 3)

Original tuple : ('meetul', 'shraddha', 'manish')
New tuple : ('meetul', 'shraddha', 'manish', 'meetul', 'shraddha', 'manish', 'meetul', 'shraddha', 'manish')


#### 17. creating tuple and count appearance of an element

In [25]:
t1 = (1,2,3,4,1,1,5,6,7,8,9)
t2 = ("meetul", "yash", "harshal")

print("Count of 1 in t1 is :", t1.count(1))
print("Count of meetul in t2 is :",t2.count("meetul"))

Count of 1 in t1 is : 3
Count of meetul in t2 is : 1


#### 18. find index of an element and index of 3 after 4

In [26]:
t1 = (1,2,3,4,1,1,5,6,7,8,9)
print("First occurence of 2 is at:",t1.index(2))
print("First occurence of 1 after 3rd index is", t1.index(1,3))

First occurence of 2 is at: 1
First occurence of 1 after 3rd index is 4


#### 19. in, not in operator in tuple

In [27]:
t2 = ("meetul", "yash", "harshal")

print("meetul" in t2)
print("jalay" in t2)

print("joyaal" not in t2)

True
False
True


#### 20. loop iteration in tuple

In [29]:
t2 = ("meetul", "yash", "harshal")

for i in t2:
    print(i, end = " ")

meetul yash harshal 

#### 21. concate two tuples 

In [30]:
t2 = ("meetul", "yash", "harshal")
print(t2 + (1,23,34))

('meetul', 'yash', 'harshal', 1, 23, 34)


#### 22. set creation and finding its datatype

In [34]:
se1 = set([1,2,3,4,1,2,3])
print(se1)
print(type(se1))
for i in se1:
    print(i,end = " ")
print()
se2 = {}
print(type(se2))
se3 = set()
print(type(se3))

{1, 2, 3, 4}
<class 'set'>
1 2 3 4 
<class 'dict'>
<class 'set'>


#### 23. to add new element in set 

In [37]:
se1 = set([1,2,3,4,1,2,3])
print("Original set is :", se1)
se1.add(6)
se1.add(7)
print("Modified set is :",se1)

Original set is : {1, 2, 3, 4}
Modified set is : {1, 2, 3, 4, 6, 7}


#### 24. updating set

In [ ]:
se1 = set([1,2,3,4,1,2,3])
print("Original set is :", se1)
se1.update([0,9,8,8,9,4])
print("Updating the OG set :",se1)

#### 25. discarding the tuple (one element at a time)

In [38]:
se1 = set([1,2,3,4,1,2,3])
se1.discard(2)
se1

{1, 3, 4}

#### 26. removing multiple elements from a tuple

In [41]:
se1 = set([1,2,3,4,1,2,3])
se1.remove(2)
se1

{1, 3, 4}

#### 27. pop() to removes last element

In [43]:
se1 = set([1,2,3,4,1,2,3])
print(se1)
se1.pop()
se1.pop()
se1

{1, 2, 3, 4}


{3, 4}

#### 28. clearing the set

In [46]:
se4 = set([1,2,3,4,1,2,3])
se4.clear()
se4

set()

#### 29. union of two sets

In [48]:
se1 = {1,2,3,4,5}
se2 = {4,5,6,7,8}
print("Union is :", se1|se2)
print("Union is :",se1.union(se2))

Union is : {1, 2, 3, 4, 5, 6, 7, 8}
Union is : {1, 2, 3, 4, 5, 6, 7, 8}


#### 30. intersection of two sets

In [49]:
se1 = {1,2,3,4,5}
se2 = {4,5,6,7,8}
print("Intersect is :", se1&se2)
print("Intersect is :",se1.intersection(se2))

Intersect is : {4, 5}
Intersect is : {4, 5}


#### 31. difference of two sets

In [50]:
se1 = {1,2,3,4,5}
se2 = {4,5,6,7,8}
print("Difference is :", se1-se2)
print("Difference is :",se1.difference(se2))

Difference is : {1, 2, 3}
Difference is : {1, 2, 3}


#### 32. superset and subset and equalset

In [52]:
se1 = {1,2,3,4,5}
se2 = {1,2}
se3 = {6,7,1}

print(se1>se2)
print(se1<se2)
print(se2 == se3)

True
False
False


#### 33. Numpy

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

print(np.__version__)

print(type(arr))

[1 2 3 4 5]
1.26.1
<class 'numpy.ndarray'>


#### 34. 0D array with value of 42

In [4]:
arr1 = np.array(42)
print(arr1)

42


#### 35. 1D array and 2D array

In [55]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1)
print()
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[1 2 3 4 5 6]

[[1 2 3]
 [4 5 6]]


#### 36. 3D array and 5D array

In [60]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr3)

arr5 = np.array([1,2,3,4],ndmin=5)
arr5

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


array([[[[[1, 2, 3, 4]]]]])

#### 37. indexing numpy and add 3rd and 4th element 

In [13]:
arr = np.array([1,2,3,4,5])
print(arr[1])
print(arr[2] + arr[3])

2
7


#### 38. access element in 2D array

In [15]:
# access element in 2D array
arr = np.array([[1,2,3],[4,5,6]])
print("2nd element in 1st row :", arr[0][1])

# slicing from index 1 to 5
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[1:5])

2nd element in 1st row : 2
[2 3 4 5]


#### 39. slicing from index 1 to 5 and stepping 2

In [16]:
# slicing from index 1 to 5 and stepping 2
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[1:5:2])

# every other element
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[::2])

[2 4]
[1 3 5 7]


#### 40. np array datatypes

In [17]:
# np array datatypes

arr = np.array(["Jerry", "Cherry"])
print(arr.dtype)

arr = np.array([1,2,3,4], dtype = 'S')
print(arr.dtype)

<U6
|S1


#### 41. create 4 bytes integer array

In [21]:
# create 4 bytes integer array
arr = np.array([1,2,3,4], dtype = 'i4')
print(arr)
print(arr.dtype)

# datatype alter np.array
arr = np.array([1.1,2.6,3,4])
newarr = arr.astype(int)
print(newarr)

[1 2 3 4]
int32
[1 2 3 4]


#### 42. copy the array, modify and display the OG

In [23]:
# copy the array, modify and display the OG
arr = np.array([1,2,3,4])
x = arr.copy()
arr[0] = 42

print("Copy :", x)
print("OG :",arr)

Copy : [1 2 3 4]
OG : [42  2  3  4]


#### 43. iteration of 2D array

In [25]:
# iteration of 2D array
arr = np.array([[1,2,3,11],[4,5,6,12]])
for i in arr:
    print(i)
for i in np.nditer(arr[:,::2]):
    print(i)

[ 1  2  3 11]
[ 4  5  6 12]
1
3
4
6


#### 44. stacking, same as concat but along a new axis

In [30]:
# stacking, same as concat but along a new axis
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1, arr2), axis=1)
arr

array([[1, 4],
       [2, 5],
       [3, 6]])

#### 45. splitting the array

In [34]:
# splitting the array
arr = np.array([1,2,3,4,5,6,7,8])
x = np.array_split(arr,3)
print(x)
print(x[0])
print(x[1])

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]
[1 2 3]
[4 5 6]


#### 46. index finding

In [36]:
# index finding
arr = np.array([1,2,3,4,5,6,7,8])
x = np.where(arr == 4)
print("4 is at",x,"position")
x = np.where(arr%2 == 0)
print("even numbers are at",x,"positions")

4 is at (array([3], dtype=int64),) position
even numbers are at (array([1, 3, 5, 7], dtype=int64),) positions


#### 47. sorting

In [37]:
# sorting
arr = np.array([1,2,5,6,7,8,3,4])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


#### 48. filtering array

In [38]:
# filtering array
arr = np.array([12, 15, 18, 19])
emt_arr = []

for i in arr:
    if i > 13:
        emt_arr.append(True)
    else:
        emt_arr.append(False)
new_arr = arr[emt_arr]
print(emt_arr)
print(new_arr)

[False, True, True, True]
[15 18 19]


#### 49. Random choosing

In [41]:
from numpy import random
print(random.choice([2,4,6,8], p=[0.1, 0.3, 0.6, 0.0],size = (200)))

[4 4 6 6 4 6 6 4 6 6 6 4 6 6 6 6 4 6 4 4 4 6 6 4 6 6 6 6 6 4 6 4 6 4 4 6 6
 6 4 2 6 2 6 6 4 4 6 6 6 6 6 4 2 4 4 4 6 6 4 4 6 4 6 6 2 4 2 6 6 4 6 2 6 6
 6 4 6 4 6 6 6 6 6 6 6 2 2 6 6 4 6 2 6 6 6 6 2 4 2 6 4 6 6 6 4 6 2 6 4 4 6
 4 6 2 4 2 6 6 2 6 2 6 6 4 6 2 4 4 6 6 2 6 6 6 6 6 6 4 4 6 6 6 6 6 4 6 2 6
 6 6 6 4 6 2 6 6 6 4 2 4 6 4 6 6 4 6 6 2 4 6 6 6 2 4 6 4 6 4 6 4 6 4 4 6 4
 4 6 6 2 4 4 2 6 4 6 4 6 2 4 4]
